# 数据集

## 西瓜数据集

In [7]:
import pandas as pd
 
def createDataSet_2():
    dataSet_2 = [
        # 1
        ['青绿', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', '好瓜'],
        # 2
        ['乌黑', '蜷缩', '沉闷', '清晰', '凹陷', '硬滑', '好瓜'],
        # 3
        ['乌黑', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', '好瓜'],
        # 4
        ['青绿', '蜷缩', '沉闷', '清晰', '凹陷', '硬滑', '好瓜'],
        # 5
        ['浅白', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', '好瓜'],
        # 6
        ['青绿', '稍蜷', '浊响', '清晰', '稍凹', '软粘', '好瓜'],
        # 7
        ['乌黑', '稍蜷', '浊响', '稍糊', '稍凹', '软粘', '好瓜'],
        # 8
        ['乌黑', '稍蜷', '浊响', '清晰', '稍凹', '硬滑', '好瓜'],
        # 9
        ['乌黑', '稍蜷', '沉闷', '稍糊', '稍凹', '硬滑', '坏瓜'],
        # 10
        ['青绿', '硬挺', '清脆', '清晰', '平坦', '软粘', '坏瓜'],
        # 11
        ['浅白', '硬挺', '清脆', '模糊', '平坦', '硬滑', '坏瓜'],
        # 12
        ['浅白', '蜷缩', '浊响', '模糊', '平坦', '软粘', '坏瓜'],
        # 13
        ['青绿', '稍蜷', '浊响', '稍糊', '凹陷', '硬滑', '坏瓜'],
        # 14
        ['浅白', '稍蜷', '沉闷', '稍糊', '凹陷', '硬滑', '坏瓜'],
        # 15
        ['乌黑', '稍蜷', '浊响', '清晰', '稍凹', '软粘', '坏瓜'],
        # 16
        ['浅白', '蜷缩', '浊响', '模糊', '平坦', '硬滑', '坏瓜'],
        # 17
        ['青绿', '蜷缩', '沉闷', '稍糊', '稍凹', '硬滑', '坏瓜']
    ]
 
    # 特征值列表
    labels_2 = ['色泽', '根蒂', '敲击', '纹理', '脐部', '触感', '好瓜']
    return dataSet_2, labels_2
 
 
 
def createDataSet_3():
    dataSet_3 = [
        # 1
        ['青绿', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', 0.697, 0.460, '好瓜'],
        # 2
        ['乌黑', '蜷缩', '沉闷', '清晰', '凹陷', '硬滑', 0.774, 0.376, '好瓜'],
        # 3
        ['乌黑', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', 0.634, 0.264, '好瓜'],
        # 4
        ['青绿', '蜷缩', '沉闷', '清晰', '凹陷', '硬滑', 0.608, 0.318, '好瓜'],
        # 5
        ['浅白', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', 0.556, 0.215, '好瓜'],
        # 6
        ['青绿', '稍蜷', '浊响', '清晰', '稍凹', '软粘', 0.403, 0.237, '好瓜'],
        # 7
        ['乌黑', '稍蜷', '浊响', '稍糊', '稍凹', '软粘', 0.481, 0.149, '好瓜'],
        # 8
        ['乌黑', '稍蜷', '浊响', '清晰', '稍凹', '硬滑', 0.437, 0.211, '好瓜'],
        # 9
        ['乌黑', '稍蜷', '沉闷', '稍糊', '稍凹', '硬滑', 0.666, 0.091, '坏瓜'],
        # 10
        ['青绿', '硬挺', '清脆', '清晰', '平坦', '软粘', 0.243, 0.267, '坏瓜'],
        # 11
        ['浅白', '硬挺', '清脆', '模糊', '平坦', '硬滑', 0.245, 0.057, '坏瓜'],
        # 12
        ['浅白', '蜷缩', '浊响', '模糊', '平坦', '软粘', 0.343, 0.099, '坏瓜'],
        # 13
        ['青绿', '稍蜷', '浊响', '稍糊', '凹陷', '硬滑', 0.639, 0.161, '坏瓜'],
        # 14
        ['浅白', '稍蜷', '沉闷', '稍糊', '凹陷', '硬滑', 0.657, 0.198, '坏瓜'],
        # 15
        ['乌黑', '稍蜷', '浊响', '清晰', '稍凹', '软粘', 0.360, 0.370, '坏瓜'],
        # 16
        ['浅白', '蜷缩', '浊响', '模糊', '平坦', '硬滑', 0.593, 0.042, '坏瓜'],
        # 17
        ['青绿', '蜷缩', '沉闷', '稍糊', '稍凹', '硬滑', 0.719, 0.103, '坏瓜']
    ]
 
    # 特征值列表
    labels_3 = ['色泽', '根蒂', '敲击', '纹理', '脐部', '触感', '密度', '含糖率','好瓜']
    return dataSet_3, labels_3
 
def createDataSet_4():
    dataSet_4 = [
        # 1
        [0.697, 0.460, '好瓜'],
        # 2
        [0.774, 0.376, '好瓜'],
        # 3
        [0.634, 0.264, '好瓜'],
        # 4
        [0.608, 0.318, '好瓜'],
        # 5
        [0.556, 0.215, '好瓜'],
        # 6
        [0.403, 0.237, '好瓜'],
        # 7
        [0.481, 0.149, '好瓜'],
        # 8
        [0.437, 0.211, '好瓜'],
        # 9
        [0.666, 0.091, '坏瓜'],
        # 10
        [0.243, 0.267, '坏瓜'],
        # 11
        [0.245, 0.057, '坏瓜'],
        # 12
        [0.343, 0.099, '坏瓜'],
        # 13
        [0.639, 0.161, '坏瓜'],
        # 14
        [0.657, 0.198, '坏瓜'],
        # 15
        [0.360, 0.370, '坏瓜'],
        # 16
        [0.593, 0.042, '坏瓜'],
        # 17
        [0.719, 0.103, '坏瓜']
    ]
 
    # 特征值列表
    labels_4 = ['密度', '含糖率','好瓜']
    return dataSet_4, labels_4
dataSet_2,labels_2=createDataSet_2()
dataSet_3,labels_3=createDataSet_3()
dataSet_4,labels_4=createDataSet_4()
def process2df(dataSet,labels):
    label2cont={}
    for label in labels:
        if label not in label2cont.keys():
            label2cont[label]=[]
    for data in dataSet:
        for i in range(len(labels)):
            label2cont[labels[i]].append(data[i])
    return pd.DataFrame(label2cont)
df2=process2df(dataSet_2,labels_2)
df3=process2df(dataSet_3,labels_3)
df4=process2df(dataSet_4,labels_4)
df2.to_excel("watermelon2.xlsx")
df3.to_excel("watermelon3.xlsx")
df4.to_excel("watermelon4.xlsx")

In [33]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le=LabelEncoder()
df=pd.DataFrame(df2)
for key in df.columns:
    df[key]=le.fit_transform(df[key])
df.to_excel("data1.xlsx")

# 贝叶斯决策

In [21]:
import numpy as np
'''
P:先验概率
p:x的条件概率
loss:风险矩阵
'''
def Bayes(P,p,loss=[]):
    P=np.array(P)
    p=np.array(p)
    postp=P*p/(sum(P*p))
    if loss==[]:
        '''
        最小错误率决策
        '''
        return postp.argmax(),postp
    else:
        '''
        最小风险决策
        '''
        ans=[]
        for i in range(len(postp)):
            s=0
            for j in range(len(postp)):
                s+=loss[i][j]*postp[j]
            ans.append(s)
        ans=np.array(ans)
        return ans.argmin(),ans

## 例子 判断细胞正常与否

正常细胞P($\omega_1$)=0.9 异常细胞P($\omega_2$)=0.1

p(x|$\omega_1$)=0.2,p(x|$\omega_2$)=0.4

In [25]:
labels=["正常细胞","异常细胞"]
loss=[[0,6],[1,0]]
ans,ls=Bayes([0.9,0.1],[0.2,0.4])
print(labels[ans])
ans,ls=Bayes([0.9,0.1],[0.2,0.4],loss)
print(labels[ans])

正常细胞
异常细胞


# 线性模型

In [1]:
import pandas as pd
import numpy as np
df=pd.read_excel("data1.xlsx",index_col=0)
train_num=15
test_num=2
train_data=df.loc[:train_num-1,:]
test_data=df.loc[train_num:,:]
train_data

色泽  根蒂  敲击  纹理  脐部  触感  好瓜
0    2   2   1   1   0   0   1
1    0   2   0   1   0   0   1
2    0   2   1   1   0   0   1
3    2   2   0   1   0   0   1
4    1   2   1   1   0   0   1
5    2   1   1   1   2   1   1
6    0   1   1   2   2   1   1
7    0   1   1   1   2   0   1
8    0   1   0   2   2   0   0
9    2   0   2   1   1   1   0
10   1   0   2   0   1   0   0
11   1   2   1   0   1   1   0
12   2   1   1   2   0   0   0
13   1   1   0   2   0   0   0
14   0   1   1   1   2   1   0

## 基于感知器准则的二分类器

In [46]:
n=6 #输入的特征数量
m=1 #实际使用的特征数量
x=[train_data.iloc[i,:m] for i in train_data.index]
y=[train_data.iloc[i,n] for i in train_data.index]
x_test=[test_data.iloc[i-train_num,:m] for i in test_data.index]
y_test=[test_data.iloc[i-train_num,n] for i in test_data.index]
#增广
for i in range(len(x)):
    x[i]=np.append(x[i],1)
    if y[i]==0:
        x[i]=-x[i]
for i in range(len(x_test)):
    x_test[i]=np.append(x_test[i],1)
#初始权重
w=np.random.normal(0,1,(m+1))
lr=0.1
max_epoch=200
epoch=0
while True:
    cnt=0
    flag=True
    for i in range(train_num):
        if sum(w*x[i])>=0:
            continue
        flag=False
        cnt+=1
        w+=lr*x[i]
    if epoch%10==0:
        print("epoch%d"%epoch,"remain %d unfited"%cnt)
    if flag==True or epoch>max_epoch:
        break
    epoch+=1
print(w)
#预测
rightnum=0
for i in range(len(x_test)):
    ans=0
    my=0
    if y_test[i]==1:
        ans=1
        print("答案:好瓜")
    else:
        print("答案:坏瓜")
    if sum(w*x_test[i])>=0:
        print("预测:好瓜")
        my=1
    else:
        print("预测:坏瓜")
        my=0
    if my==ans:
        rightnum+=1
print("正确率:","%d%%"%(rightnum/test_num*100))

epoch0 remain 8 unfited
epoch10 remain 4 unfited
epoch20 remain 4 unfited
epoch30 remain 4 unfited
epoch40 remain 4 unfited
epoch50 remain 4 unfited
epoch60 remain 4 unfited
epoch70 remain 4 unfited
epoch80 remain 4 unfited
epoch90 remain 4 unfited
epoch100 remain 4 unfited
epoch110 remain 4 unfited
epoch120 remain 4 unfited
epoch130 remain 4 unfited
epoch140 remain 4 unfited
epoch150 remain 4 unfited
epoch160 remain 4 unfited
epoch170 remain 4 unfited
epoch180 remain 4 unfited
epoch190 remain 4 unfited
epoch200 remain 4 unfited
[ 0.03326547 -0.11921318]
答案:坏瓜
预测:坏瓜
答案:坏瓜
预测:坏瓜
正确率: 100%


# 支持向量机

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot
from sklearn import svm
from dataset import *
n=6 #输入的特征数量
m=6 #实际使用的特征数量
X,y,X_test,y_test=getData1()
clf = svm.SVC(kernel='linear')
# from sklearn.preprocessing import StandardScaler # 标准化
# scaler = StandardScaler()
# X = scaler.fit_transform(X)
# X_test = scaler.fit_transform(X_test)
clf.fit(X,y)
w = clf.coef_[0]
b = clf.intercept_[0]
y_pred=[]
for i in X_test:
    y_pred.append(sum(w*i+b))
judgeTest(y_pred,y_test)

答案:坏瓜
预测:坏瓜
答案:坏瓜
预测:坏瓜
答案:坏瓜
预测:坏瓜
正确率: 100%


# 决策树

https://www.cnblogs.com/listenfwind/p/11310924.html

In [9]:
from sklearn.feature_extraction import DictVectorizer
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
from dataset import *
vec=DictVectorizer(sparse=False)
X,y,X_test,y_test=getData1()
#criterion='gini' 'entropy'
clf = tree.DecisionTreeClassifier(criterion='entropy')
clf.fit(X,y)
with open("out.dot", 'w') as f :
    f = tree.export_graphviz(clf, out_file = f,
            feature_names = ['seze', 'gendi', 'qiaoji', 'wenli', 'jibu', 'chugan'])

C:\Users\fzc\Anaconda3\lib\site-packages\sklearn\tree\tree.py:149: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_encoded = np.zeros(y.shape, dtype=np.int)


http://www.graphviz.org/download/ 下载并添加path

使用命令导出pdf图片 dot out.dot -T pdf -o out.pdf -Gcharset=latin1

# 人工神经网络

In [26]:
import random
from dataset import *
def sigmoid(x):
    return 1/(1+np.exp(-x))
def sigmoidg(x):
    return np.exp(-x)/(pow(1 + np.exp(-x),2))
def mse(Y,y):
    return sum((Y-y)*(Y-y))/2
class Net:
    def __init__(self,n,m,k):
        self.n=n
        self.m=m
        self.k=k
        self.w1=np.random.normal(0,1,(n,m))
        self.X0=np.zeros(m)
        self.X1=np.zeros(m)
        self.X2=np.zeros(k)
        self.b1=0.1
        self.w2=np.random.normal(0,1,(m,k))
        self.b2=0.1
        self.Y=np.zeros(k)
    def forward(self):
        #输入层-隐藏层
        for i in range(self.m):
            s=self.b1
            for j in range(self.n):
                s+=self.w1[j][i]*self.X[j]
            self.X0[i]=s
        self.X1=sigmoid(self.X0)
        #隐藏层-输出层
        for i in range(self.k):
            s=self.b2
            for j in range(self.m):
                s+=self.w2[j][i]*self.X1[j]
            self.X2[i]=s
        self.Y=sigmoid(self.X2)
    def backward(self):
        loss1=self.Y-self.y
        hide_g=self.Y-self.y
        for k in range(self.k):
            loss1[k]*=sigmoidg(self.X2[k])
            hide_g[k]=loss1[k]*self.X1[k]
        input_g=[0]*self.m
        for m in range(self.m):
            for k in range(self.k):
                input_g[m]+=loss1[k]*self.w2[m][k]
            input_g[m]*=sigmoidg(self.X0[m])
        for k in range(self.k):
            for m in range(self.m):
                self.w2[m][k]-=self.lr*hide_g[k]*self.X1[m]
        for m in range(self.m):
            for n in range(self.n):
                self.w1[n][m]-=self.lr*input_g[m]*self.X[n]
        self.loss+=mse(self.Y,self.y)
    def step(self,X,y,lr):
        self.loss=0
        for i in range(len(X)):
            self.X=X[i]
            self.y=y[i]
            self.lr=lr
            self.forward()
            self.backward()
    def pred(self,X):
        ans=[]
        for i in range(len(X)):
            self.X=X[i]
            self.forward()
            ans.append(self.Y)
        return ans
X,y,X_test,y_test=getData1(0.8)
net=Net(6,4,1)
epoch=10000
for i in range(epoch):
    net.step(X,y,0.1)
    loss=net.loss
    if loss<0.01:
        break
    print("epoch %d"%i,"loss:",loss)
net.pred(X),y

epoch 0 loss: 3.4101518042499297
epoch 1 loss: 3.3575395355609086
epoch 2 loss: 3.2977908244234784
epoch 3 loss: 3.229912828398758
epoch 4 loss: 3.1528756653087644
epoch 5 loss: 3.0656911908692717
epoch 6 loss: 2.9675503533084955
epoch 7 loss: 2.858041103687006
epoch 8 loss: 2.7374577938163487
epoch 9 loss: 2.607174385073339
epoch 10 loss: 2.46997647500551
epoch 11 loss: 2.3301515808588555
epoch 12 loss: 2.1931090520519385
epoch 13 loss: 2.0644611312947947
epoch 14 loss: 1.9488401491945602
epoch 15 loss: 1.848987745051495
epoch 16 loss: 1.7655248011189286
epoch 17 loss: 1.697375715872338
epoch 18 loss: 1.6424890839999877
epoch 19 loss: 1.5984960881900259
epoch 20 loss: 1.5631405634404532
epoch 21 loss: 1.5344843853416474
epoch 22 loss: 1.5109611754256065
epoch 23 loss: 1.4913508660867527
epoch 24 loss: 1.4747237242853013
epoch 25 loss: 1.4603798030081352
epoch 26 loss: 1.4477950658840624
epoch 27 loss: 1.4365775640145126
epoch 28 loss: 1.4264334693908938
epoch 29 loss: 1.41714146452317

epoch 337 loss: 0.725130573349535
epoch 338 loss: 0.7232812648194393
epoch 339 loss: 0.7214321262923045
epoch 340 loss: 0.7195857465067782
epoch 341 loss: 0.717744910151997
epoch 342 loss: 0.7159125865043074
epoch 343 loss: 0.714091913311332
epoch 344 loss: 0.7122861757087439
epoch 345 loss: 0.7104987801194789
epoch 346 loss: 0.708733223281159
epoch 347 loss: 0.7069930567673527
epoch 348 loss: 0.7052818476006081
epoch 349 loss: 0.7036031357851854
epoch 350 loss: 0.7019603897981794
epoch 351 loss: 0.7003569612515571
epoch 352 loss: 0.6987960400579342
epoch 353 loss: 0.6972806114860963
epoch 354 loss: 0.6958134164697758
epoch 355 loss: 0.6943969164326195
epoch 356 loss: 0.6930332637182658
epoch 357 loss: 0.6917242784783637
epoch 358 loss: 0.6904714325901145
epoch 359 loss: 0.6892758408693354
epoch 360 loss: 0.6881382595373178
epoch 361 loss: 0.687059091611208
epoch 362 loss: 0.6860383986365176
epoch 363 loss: 0.6850759179801867
epoch 364 loss: 0.6841710847613655
epoch 365 loss: 0.6833230

epoch 705 loss: 0.5005579935018099
epoch 706 loss: 0.5000502034085983
epoch 707 loss: 0.49954845327619546
epoch 708 loss: 0.4990525857754787
epoch 709 loss: 0.49856244840296726
epoch 710 loss: 0.49807789331264996
epoch 711 loss: 0.4975987771550629
epoch 712 loss: 0.4971249609232097
epoch 713 loss: 0.4966563098049395
epoch 714 loss: 0.49619269304142566
epoch 715 loss: 0.4957339837914063
epoch 716 loss: 0.495280059000887
epoch 717 loss: 0.49483079927800433
epoch 718 loss: 0.49438608877278994
epoch 719 loss: 0.49394581506157714
epoch 720 loss: 0.4935098690358183
epoch 721 loss: 0.49307814479509005
epoch 722 loss: 0.49265053954408833
epoch 723 loss: 0.4922269534934106
epoch 724 loss: 0.49180728976395527
epoch 725 loss: 0.49139145429476433
epoch 726 loss: 0.4909793557541537
epoch 727 loss: 0.4905709054539816
epoch 728 loss: 0.49016601726691683
epoch 729 loss: 0.4897646075465776
epoch 730 loss: 0.48936659505041213
epoch 731 loss: 0.4889719008652136
epoch 732 loss: 0.48858044833514974
epoch 7

epoch 1057 loss: 0.41187323293463096
epoch 1058 loss: 0.4116929508708115
epoch 1059 loss: 0.4115128449179439
epoch 1060 loss: 0.411332914866411
epoch 1061 loss: 0.4111531605143679
epoch 1062 loss: 0.4109735816676734
epoch 1063 loss: 0.4107941781398212
epoch 1064 loss: 0.41061494975187146
epoch 1065 loss: 0.4104358963323798
epoch 1066 loss: 0.4102570177173292
epoch 1067 loss: 0.41007831375005843
epoch 1068 loss: 0.4098997842811917
epoch 1069 loss: 0.409721429168569
epoch 1070 loss: 0.4095432482771723
epoch 1071 loss: 0.40936524147905645
epoch 1072 loss: 0.409187408653274
epoch 1073 loss: 0.4090097496858065
epoch 1074 loss: 0.4088322644694885
epoch 1075 loss: 0.4086549529039359
epoch 1076 loss: 0.408477814895472
epoch 1077 loss: 0.4083008503570546
epoch 1078 loss: 0.4081240592081997
epoch 1079 loss: 0.4079474413749098
epoch 1080 loss: 0.40777099678959633
epoch 1081 loss: 0.4075947253910064
epoch 1082 loss: 0.4074186271241466
epoch 1083 loss: 0.40724270194020723
epoch 1084 loss: 0.4070669

epoch 1449 loss: 0.35518754493834653
epoch 1450 loss: 0.35507868177448804
epoch 1451 loss: 0.3549699808296659
epoch 1452 loss: 0.3548614418623127
epoch 1453 loss: 0.35475306463084166
epoch 1454 loss: 0.35464484889365355
epoch 1455 loss: 0.354536794409143
epoch 1456 loss: 0.3544289009357045
epoch 1457 loss: 0.35432116823173954
epoch 1458 loss: 0.3542135960556612
epoch 1459 loss: 0.3541061841659025
epoch 1460 loss: 0.35399893232092094
epoch 1461 loss: 0.35389184027920534
epoch 1462 loss: 0.35378490779928046
epoch 1463 loss: 0.35367813463971426
epoch 1464 loss: 0.35357152055912205
epoch 1465 loss: 0.35346506531617333
epoch 1466 loss: 0.35335876866959764
epoch 1467 loss: 0.35325263037818727
epoch 1468 loss: 0.3531466502008055
epoch 1469 loss: 0.35304082789639113
epoch 1470 loss: 0.3529351632239632
epoch 1471 loss: 0.352829655942625
epoch 1472 loss: 0.3527243058115717
epoch 1473 loss: 0.35261911259009315
epoch 1474 loss: 0.35251407603757945
epoch 1475 loss: 0.35240919591352493
epoch 1476 lo

epoch 1880 loss: 0.3203966130939346
epoch 1881 loss: 0.3203382841890924
epoch 1882 loss: 0.3202800358434906
epoch 1883 loss: 0.3202218679238803
epoch 1884 loss: 0.32016378029723264
epoch 1885 loss: 0.320105772830742
epoch 1886 loss: 0.3200478453918197
epoch 1887 loss: 0.3199899978480992
epoch 1888 loss: 0.31993223006743154
epoch 1889 loss: 0.31987454191788806
epoch 1890 loss: 0.3198169332677598
epoch 1891 loss: 0.31975940398555447
epoch 1892 loss: 0.3197019539400006
epoch 1893 loss: 0.31964458300004306
epoch 1894 loss: 0.3195872910348445
epoch 1895 loss: 0.31953007791378624
epoch 1896 loss: 0.3194729435064654
epoch 1897 loss: 0.31941588768269813
epoch 1898 loss: 0.3193589103125155
epoch 1899 loss: 0.319302011266166
epoch 1900 loss: 0.3192451904141129
epoch 1901 loss: 0.31918844762703696
epoch 1902 loss: 0.31913178277583415
epoch 1903 loss: 0.3190751957316144
epoch 1904 loss: 0.31901868636570474
epoch 1905 loss: 0.3189622545496444
epoch 1906 loss: 0.31890590015519
epoch 1907 loss: 0.318

epoch 2290 loss: 0.30194702527077316
epoch 2291 loss: 0.30191275365136705
epoch 2292 loss: 0.30187852338707344
epoch 2293 loss: 0.30184433441293185
epoch 2294 loss: 0.3018101866640994
epoch 2295 loss: 0.3017760800758493
epoch 2296 loss: 0.30174201458357147
epoch 2297 loss: 0.30170799012277294
epoch 2298 loss: 0.3016740066290749
epoch 2299 loss: 0.30164006403821514
epoch 2300 loss: 0.3016061622860483
epoch 2301 loss: 0.3015723013085426
epoch 2302 loss: 0.3015384810417821
epoch 2303 loss: 0.3015047014219664
epoch 2304 loss: 0.30147096238540905
epoch 2305 loss: 0.30143726386853803
epoch 2306 loss: 0.3014036058078966
epoch 2307 loss: 0.3013699881401413
epoch 2308 loss: 0.3013364108020428
epoch 2309 loss: 0.30130287373048564
epoch 2310 loss: 0.30126937686246824
epoch 2311 loss: 0.3012359201351014
epoch 2312 loss: 0.3012025034856096
epoch 2313 loss: 0.30116912685132974
epoch 2314 loss: 0.3011357901697125
epoch 2315 loss: 0.30110249337831996
epoch 2316 loss: 0.30106923641482675
epoch 2317 los

epoch 2648 loss: 0.2918972970765408
epoch 2649 loss: 0.29187443729835183
epoch 2650 loss: 0.29185160168043056
epoch 2651 loss: 0.2918287901883356
epoch 2652 loss: 0.29180600278768565
epoch 2653 loss: 0.29178323944415824
epoch 2654 loss: 0.29176050012348986
epoch 2655 loss: 0.2917377847914771
epoch 2656 loss: 0.2917150934139733
epoch 2657 loss: 0.29169242595689293
epoch 2658 loss: 0.2916697823862072
epoch 2659 loss: 0.2916471626679475
epoch 2660 loss: 0.29162456676820186
epoch 2661 loss: 0.2916019946531187
epoch 2662 loss: 0.2915794462889022
epoch 2663 loss: 0.2915569216418176
epoch 2664 loss: 0.2915344206781855
epoch 2665 loss: 0.29151194336438524
epoch 2666 loss: 0.2914894896668543
epoch 2667 loss: 0.2914670595520881
epoch 2668 loss: 0.29144465298663796
epoch 2669 loss: 0.2914222699371143
epoch 2670 loss: 0.2913999103701837
epoch 2671 loss: 0.2913775742525717
epoch 2672 loss: 0.2913552615510586
epoch 2673 loss: 0.2913329722324836
epoch 2674 loss: 0.29131070626374134
epoch 2675 loss: 0

epoch 3118 loss: 0.28332450801922443
epoch 3119 loss: 0.28331003535446164
epoch 3120 loss: 0.2832955756227707
epoch 3121 loss: 0.28328112880816947
epoch 3122 loss: 0.2832666948947009
epoch 3123 loss: 0.2832522738664325
epoch 3124 loss: 0.28323786570745624
epoch 3125 loss: 0.28322347040188806
epoch 3126 loss: 0.2832090879338692
epoch 3127 loss: 0.28319471828756393
epoch 3128 loss: 0.28318036144716285
epoch 3129 loss: 0.2831660173968783
epoch 3130 loss: 0.28315168612094904
epoch 3131 loss: 0.2831373676036366
epoch 3132 loss: 0.2831230618292279
epoch 3133 loss: 0.28310876878203195
epoch 3134 loss: 0.28309448844638446
epoch 3135 loss: 0.28308022080664264
epoch 3136 loss: 0.28306596584718957
epoch 3137 loss: 0.2830517235524306
epoch 3138 loss: 0.2830374939067967
epoch 3139 loss: 0.2830232768947412
epoch 3140 loss: 0.2830090725007421
epoch 3141 loss: 0.28299488070930046
epoch 3142 loss: 0.28298070150494137
epoch 3143 loss: 0.28296653487221496
epoch 3144 loss: 0.28295238079569174
epoch 3145 l

epoch 3481 loss: 0.27880978661045236
epoch 3482 loss: 0.27879912543792906
epoch 3483 loss: 0.2787884727166774
epoch 3484 loss: 0.27877782843731597
epoch 3485 loss: 0.27876719259047766
epoch 3486 loss: 0.2787565651668074
epoch 3487 loss: 0.2787459461569628
epoch 3488 loss: 0.27873533555161567
epoch 3489 loss: 0.2787247333414502
epoch 3490 loss: 0.27871413951716384
epoch 3491 loss: 0.27870355406946645
epoch 3492 loss: 0.27869297698908174
epoch 3493 loss: 0.27868240826674573
epoch 3494 loss: 0.2786718478932074
epoch 3495 loss: 0.27866129585922905
epoch 3496 loss: 0.27865075215558527
epoch 3497 loss: 0.27864021677306366
epoch 3498 loss: 0.27862968970246516
epoch 3499 loss: 0.27861917093460326
epoch 3500 loss: 0.2786086604603035
epoch 3501 loss: 0.2785981582704054
epoch 3502 loss: 0.2785876643557601
epoch 3503 loss: 0.27857717870723225
epoch 3504 loss: 0.2785667013156993
epoch 3505 loss: 0.2785562321720504
epoch 3506 loss: 0.2785457712671884
epoch 3507 loss: 0.27853531859202824
epoch 3508 l

epoch 3814 loss: 0.275675515573732
epoch 3815 loss: 0.2756672203554458
epoch 3816 loss: 0.27565893107485906
epoch 3817 loss: 0.2756506477259685
epoch 3818 loss: 0.27564237030277766
epoch 3819 loss: 0.2756340987992985
epoch 3820 loss: 0.2756258332095506
epoch 3821 loss: 0.2756175735275612
epoch 3822 loss: 0.2756093197473649
epoch 3823 loss: 0.2756010718630035
epoch 3824 loss: 0.2755928298685278
epoch 3825 loss: 0.2755845937579951
epoch 3826 loss: 0.2755763635254708
epoch 3827 loss: 0.27556813916502765
epoch 3828 loss: 0.275559920670746
epoch 3829 loss: 0.2755517080367138
epoch 3830 loss: 0.2755435012570275
epoch 3831 loss: 0.2755353003257882
epoch 3832 loss: 0.27552710523710894
epoch 3833 loss: 0.27551891598510664
epoch 3834 loss: 0.2755107325639074
epoch 3835 loss: 0.27550255496764386
epoch 3836 loss: 0.2754943831904573
epoch 3837 loss: 0.27548621722649524
epoch 3838 loss: 0.27547805706991463
epoch 3839 loss: 0.2754699027148774
epoch 3840 loss: 0.27546175415555496
epoch 3841 loss: 0.27

epoch 4062 loss: 0.2737861854318394
epoch 4063 loss: 0.2737791965581088
epoch 4064 loss: 0.2737722123423658
epoch 4065 loss: 0.27376523278020215
epoch 4066 loss: 0.2737582578672151
epoch 4067 loss: 0.273751287599007
epoch 4068 loss: 0.27374432197118514
epoch 4069 loss: 0.27373736097936224
epoch 4070 loss: 0.27373040461915615
epoch 4071 loss: 0.2737234528861903
epoch 4072 loss: 0.2737165057760948
epoch 4073 loss: 0.2737095632845013
epoch 4074 loss: 0.27370262540705026
epoch 4075 loss: 0.27369569213938616
epoch 4076 loss: 0.273688763477158
epoch 4077 loss: 0.2736818394160214
epoch 4078 loss: 0.2736749199516363
epoch 4079 loss: 0.27366800507966804
epoch 4080 loss: 0.2736610947957866
epoch 4081 loss: 0.2736541890956684
epoch 4082 loss: 0.2736472879749947
epoch 4083 loss: 0.27364039142945146
epoch 4084 loss: 0.2736334994547294
epoch 4085 loss: 0.2736266120465255
epoch 4086 loss: 0.2736197292005417
epoch 4087 loss: 0.27361285091248455
epoch 4088 loss: 0.27360597717806656
epoch 4089 loss: 0.2

epoch 4314 loss: 0.2721614985563419
epoch 4315 loss: 0.27215555692918153
epoch 4316 loss: 0.2721496189989638
epoch 4317 loss: 0.2721436847624082
epoch 4318 loss: 0.27213775421623654
epoch 4319 loss: 0.2721318273571768
epoch 4320 loss: 0.272125904181957
epoch 4321 loss: 0.2721199846873124
epoch 4322 loss: 0.2721140688699799
epoch 4323 loss: 0.2721081567267004
epoch 4324 loss: 0.2721022482542194
epoch 4325 loss: 0.2720963434492847
epoch 4326 loss: 0.27209044230864926
epoch 4327 loss: 0.2720845448290689
epoch 4328 loss: 0.2720786510073029
epoch 4329 loss: 0.2720727608401149
epoch 4330 loss: 0.27206687432427157
epoch 4331 loss: 0.2720609914565434
epoch 4332 loss: 0.2720551122337054
epoch 4333 loss: 0.2720492366525346
epoch 4334 loss: 0.27204336470981344
epoch 4335 loss: 0.2720374964023263
epoch 4336 loss: 0.2720316317268625
epoch 4337 loss: 0.2720257706802147
epoch 4338 loss: 0.27201991325917885
epoch 4339 loss: 0.27201405946055407
epoch 4340 loss: 0.2720082092811447
epoch 4341 loss: 0.272

epoch 4647 loss: 0.2703690054488827
epoch 4648 loss: 0.2703641339469536
epoch 4649 loss: 0.2703592652279758
epoch 4650 loss: 0.2703543992896706
epoch 4651 loss: 0.27034953612976115
epoch 4652 loss: 0.27034467574597354
epoch 4653 loss: 0.27033981813603664
epoch 4654 loss: 0.27033496329768114
epoch 4655 loss: 0.27033011122863976
epoch 4656 loss: 0.2703252619266488
epoch 4657 loss: 0.2703204153894463
epoch 4658 loss: 0.2703155716147725
epoch 4659 loss: 0.2703107306003694
epoch 4660 loss: 0.2703058923439833
epoch 4661 loss: 0.27030105684336136
epoch 4662 loss: 0.27029622409625276
epoch 4663 loss: 0.2702913941004102
epoch 4664 loss: 0.2702865668535885
epoch 4665 loss: 0.27028174235354496
epoch 4666 loss: 0.2702769205980376
epoch 4667 loss: 0.27027210158482873
epoch 4668 loss: 0.27026728531168304
epoch 4669 loss: 0.27026247177636603
epoch 4670 loss: 0.2702576609766467
epoch 4671 loss: 0.2702528529102962
epoch 4672 loss: 0.2702480475750877
epoch 4673 loss: 0.27024324496879687
epoch 4674 loss:

epoch 5083 loss: 0.26848088645114976
epoch 5084 loss: 0.2684770411285693
epoch 5085 loss: 0.26847319778693773
epoch 5086 loss: 0.26846935642478464
epoch 5087 loss: 0.26846551704064175
epoch 5088 loss: 0.2684616796330425
epoch 5089 loss: 0.26845784420052093
epoch 5090 loss: 0.26845401074161296
epoch 5091 loss: 0.2684501792548558
epoch 5092 loss: 0.26844634973878845
epoch 5093 loss: 0.2684425221919501
epoch 5094 loss: 0.26843869661288267
epoch 5095 loss: 0.2684348730001291
epoch 5096 loss: 0.26843105135223305
epoch 5097 loss: 0.2684272316677408
epoch 5098 loss: 0.2684234139451989
epoch 5099 loss: 0.26841959818315586
epoch 5100 loss: 0.2684157843801612
epoch 5101 loss: 0.2684119725347667
epoch 5102 loss: 0.2684081626455248
epoch 5103 loss: 0.26840435471098856
epoch 5104 loss: 0.2684005487297142
epoch 5105 loss: 0.2683967447002579
epoch 5106 loss: 0.2683929426211783
epoch 5107 loss: 0.26838914249103424
epoch 5108 loss: 0.26838534430838706
epoch 5109 loss: 0.26838154807179865
epoch 5110 los

epoch 5313 loss: 0.26764584087827265
epoch 5314 loss: 0.26764241511237874
epoch 5315 loss: 0.2676389910234547
epoch 5316 loss: 0.267635568610315
epoch 5317 loss: 0.26763214787177714
epoch 5318 loss: 0.2676287288066579
epoch 5319 loss: 0.26762531141377555
epoch 5320 loss: 0.26762189569195044
epoch 5321 loss: 0.2676184816400024
epoch 5322 loss: 0.26761506925675477
epoch 5323 loss: 0.267611658541029
epoch 5324 loss: 0.2676082494916488
epoch 5325 loss: 0.26760484210744045
epoch 5326 loss: 0.2676014363872297
epoch 5327 loss: 0.2675980323298429
epoch 5328 loss: 0.26759462993410915
epoch 5329 loss: 0.26759122919885725
epoch 5330 loss: 0.26758783012291765
epoch 5331 loss: 0.2675844327051218
epoch 5332 loss: 0.267581036944303
epoch 5333 loss: 0.2675776428392931
epoch 5334 loss: 0.2675742503889283
epoch 5335 loss: 0.26757085959204363
epoch 5336 loss: 0.2675674704474764
epoch 5337 loss: 0.26756408295406336
epoch 5338 loss: 0.26756069711064423
epoch 5339 loss: 0.267557312916059
epoch 5340 loss: 0.

epoch 5646 loss: 0.26659104318758003
epoch 5647 loss: 0.26658811641896696
epoch 5648 loss: 0.26658519098611544
epoch 5649 loss: 0.2665822668881437
epoch 5650 loss: 0.2665793441241712
epoch 5651 loss: 0.26657642269331666
epoch 5652 loss: 0.2665735025947017
epoch 5653 loss: 0.2665705838274466
epoch 5654 loss: 0.26656766639067364
epoch 5655 loss: 0.2665647502835058
epoch 5656 loss: 0.26656183550506574
epoch 5657 loss: 0.26655892205447823
epoch 5658 loss: 0.266556009930868
epoch 5659 loss: 0.2665530991333611
epoch 5660 loss: 0.26655018966108374
epoch 5661 loss: 0.2665472815131631
epoch 5662 loss: 0.2665443746887268
epoch 5663 loss: 0.2665414691869041
epoch 5664 loss: 0.2665385650068241
epoch 5665 loss: 0.2665356621476166
epoch 5666 loss: 0.2665327606084134
epoch 5667 loss: 0.2665298603883456
epoch 5668 loss: 0.2665269614865461
epoch 5669 loss: 0.2665240639021473
epoch 5670 loss: 0.26652116763428346
epoch 5671 loss: 0.26651827268208894
epoch 5672 loss: 0.2665153790446997
epoch 5673 loss: 0.

epoch 5929 loss: 0.26581295963058293
epoch 5930 loss: 0.26581037832833837
epoch 5931 loss: 0.265807798139759
epoch 5932 loss: 0.2658052190641488
epoch 5933 loss: 0.2658026411008126
epoch 5934 loss: 0.26580006424905434
epoch 5935 loss: 0.26579748850818136
epoch 5936 loss: 0.2657949138774992
epoch 5937 loss: 0.2657923403563141
epoch 5938 loss: 0.2657897679439338
epoch 5939 loss: 0.26578719663966627
epoch 5940 loss: 0.26578462644282014
epoch 5941 loss: 0.2657820573527041
epoch 5942 loss: 0.2657794893686277
epoch 5943 loss: 0.2657769224899019
epoch 5944 loss: 0.2657743567158361
epoch 5945 loss: 0.2657717920457428
epoch 5946 loss: 0.26576922847893336
epoch 5947 loss: 0.2657666660147198
epoch 5948 loss: 0.26576410465241573
epoch 5949 loss: 0.26576154439133426
epoch 5950 loss: 0.2657589852307898
epoch 5951 loss: 0.2657564271700963
epoch 5952 loss: 0.2657538702085695
epoch 5953 loss: 0.26575131434552524
epoch 5954 loss: 0.2657487595802798
epoch 5955 loss: 0.26574620591214954
epoch 5956 loss: 0

epoch 6312 loss: 0.26489978720381796
epoch 6313 loss: 0.26489758632434807
epoch 6314 loss: 0.26489538632869364
epoch 6315 loss: 0.26489318721633914
epoch 6316 loss: 0.26489098898677116
epoch 6317 loss: 0.26488879163947504
epoch 6318 loss: 0.2648865951739372
epoch 6319 loss: 0.2648843995896439
epoch 6320 loss: 0.26488220488608266
epoch 6321 loss: 0.26488001106274134
epoch 6322 loss: 0.2648778181191069
epoch 6323 loss: 0.26487562605466775
epoch 6324 loss: 0.26487343486891335
epoch 6325 loss: 0.264871244561332
epoch 6326 loss: 0.2648690551314134
epoch 6327 loss: 0.2648668665786465
epoch 6328 loss: 0.2648646789025233
epoch 6329 loss: 0.26486249210253276
epoch 6330 loss: 0.264860306178166
epoch 6331 loss: 0.26485812112891505
epoch 6332 loss: 0.2648559369542708
epoch 6333 loss: 0.26485375365372654
epoch 6334 loss: 0.26485157122677344
epoch 6335 loss: 0.2648493896729054
epoch 6336 loss: 0.26484720899161546
epoch 6337 loss: 0.26484502918239694
epoch 6338 loss: 0.2648428502447441
epoch 6339 los

epoch 6645 loss: 0.26421279529801156
epoch 6646 loss: 0.26421086248491954
epoch 6647 loss: 0.26420893040379656
epoch 6648 loss: 0.2642069990542404
epoch 6649 loss: 0.26420506843584907
epoch 6650 loss: 0.2642031385482195
epoch 6651 loss: 0.26420120939095126
epoch 6652 loss: 0.2641992809636432
epoch 6653 loss: 0.2641973532658937
epoch 6654 loss: 0.2641954262973026
epoch 6655 loss: 0.26419350005746867
epoch 6656 loss: 0.26419157454599257
epoch 6657 loss: 0.26418964976247383
epoch 6658 loss: 0.2641877257065135
epoch 6659 loss: 0.264185802377712
epoch 6660 loss: 0.2641838797756703
epoch 6661 loss: 0.26418195789998994
epoch 6662 loss: 0.2641800367502725
epoch 6663 loss: 0.2641781163261197
epoch 6664 loss: 0.2641761966271336
epoch 6665 loss: 0.2641742776529166
epoch 6666 loss: 0.2641723594030718
epoch 6667 loss: 0.2641704418772024
epoch 6668 loss: 0.2641685250749112
epoch 6669 loss: 0.26416660899580147
epoch 6670 loss: 0.26416469363947814
epoch 6671 loss: 0.26416277900554497
epoch 6672 loss: 

epoch 6968 loss: 0.26362444394129575
epoch 6969 loss: 0.26362272813022997
epoch 6970 loss: 0.26362101293488616
epoch 6971 loss: 0.2636192983549431
epoch 6972 loss: 0.26361758439008043
epoch 6973 loss: 0.26361587103997763
epoch 6974 loss: 0.26361415830431456
epoch 6975 loss: 0.26361244618277135
epoch 6976 loss: 0.26361073467502755
epoch 6977 loss: 0.2636090237807643
epoch 6978 loss: 0.26360731349966193
epoch 6979 loss: 0.26360560383140114
epoch 6980 loss: 0.26360389477566337
epoch 6981 loss: 0.26360218633212973
epoch 6982 loss: 0.2636004785004817
epoch 6983 loss: 0.26359877128040105
epoch 6984 loss: 0.26359706467156974
epoch 6985 loss: 0.2635953586736696
epoch 6986 loss: 0.263593653286384
epoch 6987 loss: 0.26359194850939455
epoch 6988 loss: 0.2635902443423841
epoch 6989 loss: 0.2635885407850359
epoch 6990 loss: 0.26358683783703385
epoch 6991 loss: 0.26358513549806056
epoch 6992 loss: 0.2635834337677994
epoch 6993 loss: 0.26358173264593565
epoch 6994 loss: 0.2635800321321519
epoch 6995 

epoch 7311 loss: 0.2630700128193643
epoch 7312 loss: 0.2630684907428774
epoch 7313 loss: 0.263066969183768
epoch 7314 loss: 0.26306544814178007
epoch 7315 loss: 0.26306392761665987
epoch 7316 loss: 0.2630624076081502
epoch 7317 loss: 0.26306088811599754
epoch 7318 loss: 0.2630593691399469
epoch 7319 loss: 0.2630578506797434
epoch 7320 loss: 0.2630563327351331
epoch 7321 loss: 0.26305481530586133
epoch 7322 loss: 0.2630532983916742
epoch 7323 loss: 0.2630517819923171
epoch 7324 loss: 0.26305026610753707
epoch 7325 loss: 0.26304875073708006
epoch 7326 loss: 0.2630472358806934
epoch 7327 loss: 0.2630457215381227
epoch 7328 loss: 0.2630442077091156
epoch 7329 loss: 0.2630426943934186
epoch 7330 loss: 0.2630411815907797
epoch 7331 loss: 0.2630396693009453
epoch 7332 loss: 0.26303815752366394
epoch 7333 loss: 0.2630366462586825
epoch 7334 loss: 0.26303513550574903
epoch 7335 loss: 0.2630336252646121
epoch 7336 loss: 0.26303211553501915
epoch 7337 loss: 0.263030606316719
epoch 7338 loss: 0.26

epoch 7730 loss: 0.2624746573507336
epoch 7731 loss: 0.26247333154665553
epoch 7732 loss: 0.2624720061659584
epoch 7733 loss: 0.2624706812084454
epoch 7734 loss: 0.2624693566739208
epoch 7735 loss: 0.2624680325621883
epoch 7736 loss: 0.262466708873052
epoch 7737 loss: 0.2624653856063157
epoch 7738 loss: 0.26246406276178413
epoch 7739 loss: 0.26246274033926154
epoch 7740 loss: 0.26246141833855285
epoch 7741 loss: 0.2624600967594621
epoch 7742 loss: 0.2624587756017943
epoch 7743 loss: 0.2624574548653544
epoch 7744 loss: 0.2624561345499473
epoch 7745 loss: 0.26245481465537823
epoch 7746 loss: 0.2624534951814525
epoch 7747 loss: 0.2624521761279751
epoch 7748 loss: 0.2624508574947514
epoch 7749 loss: 0.2624495392815884
epoch 7750 loss: 0.26244822148829006
epoch 7751 loss: 0.26244690411466287
epoch 7752 loss: 0.26244558716051325
epoch 7753 loss: 0.26244427062564646
epoch 7754 loss: 0.26244295450986926
epoch 7755 loss: 0.26244163881298754
epoch 7756 loss: 0.26244032353480845
epoch 7757 loss: 

epoch 7977 loss: 0.262159576870635
epoch 7978 loss: 0.26215834996121146
epoch 7979 loss: 0.2621571234301014
epoch 7980 loss: 0.2621558972771362
epoch 7981 loss: 0.2621546715021464
epoch 7982 loss: 0.2621534461049626
epoch 7983 loss: 0.26215222108541586
epoch 7984 loss: 0.26215099644333784
epoch 7985 loss: 0.2621497721785592
epoch 7986 loss: 0.2621485482909112
epoch 7987 loss: 0.26214732478022573
epoch 7988 loss: 0.2621461016463337
epoch 7989 loss: 0.2621448788890664
epoch 7990 loss: 0.26214365650825683
epoch 7991 loss: 0.2621424345037353
epoch 7992 loss: 0.2621412128753344
epoch 7993 loss: 0.26213999162288587
epoch 7994 loss: 0.26213877074622227
epoch 7995 loss: 0.26213755024517504
epoch 7996 loss: 0.2621363301195769
epoch 7997 loss: 0.26213511036926
epoch 7998 loss: 0.26213389099405676
epoch 7999 loss: 0.2621326719938001
epoch 8000 loss: 0.26213145336832255
epoch 8001 loss: 0.26213023511745664
epoch 8002 loss: 0.26212901724103577
epoch 8003 loss: 0.2621277997388921
epoch 8004 loss: 0.

epoch 8448 loss: 0.2616208351399956
epoch 8449 loss: 0.261619769262962
epoch 8450 loss: 0.26161870369437884
epoch 8451 loss: 0.2616176384341165
epoch 8452 loss: 0.26161657348204553
epoch 8453 loss: 0.26161550883803686
epoch 8454 loss: 0.2616144445019604
epoch 8455 loss: 0.2616133804736886
epoch 8456 loss: 0.26161231675309066
epoch 8457 loss: 0.2616112533400385
epoch 8458 loss: 0.26161019023440313
epoch 8459 loss: 0.26160912743605547
epoch 8460 loss: 0.2616080649448663
epoch 8461 loss: 0.2616070027607075
epoch 8462 loss: 0.26160594088345007
epoch 8463 loss: 0.26160487931296544
epoch 8464 loss: 0.2616038180491254
epoch 8465 loss: 0.2616027570918009
epoch 8466 loss: 0.26160169644086434
epoch 8467 loss: 0.2616006360961862
epoch 8468 loss: 0.2615995760576397
epoch 8469 loss: 0.26159851632509534
epoch 8470 loss: 0.26159745689842573
epoch 8471 loss: 0.2615963977775027
epoch 8472 loss: 0.2615953389621979
epoch 8473 loss: 0.26159428045238425
epoch 8474 loss: 0.2615932222479331
epoch 8475 loss: 

epoch 8810 loss: 0.2612541749422361
epoch 8811 loss: 0.26125321279282593
epoch 8812 loss: 0.26125225090931326
epoch 8813 loss: 0.26125128929159064
epoch 8814 loss: 0.2612503279395522
epoch 8815 loss: 0.26124936685309147
epoch 8816 loss: 0.2612484060321023
epoch 8817 loss: 0.26124744547647805
epoch 8818 loss: 0.2612464851861122
epoch 8819 loss: 0.2612455251608989
epoch 8820 loss: 0.2612445654007327
epoch 8821 loss: 0.26124360590550666
epoch 8822 loss: 0.26124264667511526
epoch 8823 loss: 0.261241687709452
epoch 8824 loss: 0.261240729008412
epoch 8825 loss: 0.2612397705718883
epoch 8826 loss: 0.26123881239977564
epoch 8827 loss: 0.26123785449196857
epoch 8828 loss: 0.26123689684836116
epoch 8829 loss: 0.2612359394688475
epoch 8830 loss: 0.2612349823533225
epoch 8831 loss: 0.26123402550168057
epoch 8832 loss: 0.26123306891381615
epoch 8833 loss: 0.2612321125896242
epoch 8834 loss: 0.2612311565289985
epoch 8835 loss: 0.26123020073183445
epoch 8836 loss: 0.26122924519802704
epoch 8837 loss:

epoch 9143 loss: 0.2609478549437148
epoch 9144 loss: 0.26094697577533044
epoch 9145 loss: 0.26094609684026865
epoch 9146 loss: 0.2609452181384395
epoch 9147 loss: 0.26094433966975344
epoch 9148 loss: 0.2609434614341205
epoch 9149 loss: 0.26094258343145216
epoch 9150 loss: 0.2609417056616576
epoch 9151 loss: 0.26094082812464847
epoch 9152 loss: 0.2609399508203347
epoch 9153 loss: 0.26093907374862696
epoch 9154 loss: 0.2609381969094361
epoch 9155 loss: 0.2609373203026731
epoch 9156 loss: 0.260936443928248
epoch 9157 loss: 0.2609355677860719
epoch 9158 loss: 0.2609346918760563
epoch 9159 loss: 0.2609338161981115
epoch 9160 loss: 0.2609329407521479
epoch 9161 loss: 0.2609320655380781
epoch 9162 loss: 0.2609311905558114
epoch 9163 loss: 0.2609303158052599
epoch 9164 loss: 0.26092944128633466
epoch 9165 loss: 0.26092856699894623
epoch 9166 loss: 0.2609276929430065
epoch 9167 loss: 0.26092681911842636
epoch 9168 loss: 0.2609259455251174
epoch 9169 loss: 0.26092507216299043
epoch 9170 loss: 0.

epoch 9476 loss: 0.26066746436146954
epoch 9477 loss: 0.26066665819446916
epoch 9478 loss: 0.26066585223326644
epoch 9479 loss: 0.2606650464777863
epoch 9480 loss: 0.2606642409279525
epoch 9481 loss: 0.2606634355836886
epoch 9482 loss: 0.2606626304449199
epoch 9483 loss: 0.2606618255115692
epoch 9484 loss: 0.26066102078356135
epoch 9485 loss: 0.26066021626082
epoch 9486 loss: 0.2606594119432702
epoch 9487 loss: 0.26065860783083505
epoch 9488 loss: 0.2606578039234399
epoch 9489 loss: 0.2606570002210087
epoch 9490 loss: 0.26065619672346496
epoch 9491 loss: 0.2606553934307349
epoch 9492 loss: 0.2606545903427412
epoch 9493 loss: 0.2606537874594097
epoch 9494 loss: 0.2606529847806638
epoch 9495 loss: 0.2606521823064286
epoch 9496 loss: 0.26065138003662824
epoch 9497 loss: 0.2606505779711883
epoch 9498 loss: 0.2606497761100324
epoch 9499 loss: 0.26064897445308577
epoch 9500 loss: 0.2606481730002729
epoch 9501 loss: 0.2606473717515186
epoch 9502 loss: 0.2606465707067479
epoch 9503 loss: 0.260

epoch 9809 loss: 0.26040994093452924
epoch 9810 loss: 0.2604091993091939
epoch 9811 loss: 0.26040845786624545
epoch 9812 loss: 0.2604077166056208
epoch 9813 loss: 0.26040697552725367
epoch 9814 loss: 0.2604062346310802
epoch 9815 loss: 0.26040549391703477
epoch 9816 loss: 0.2604047533850536
epoch 9817 loss: 0.26040401303507116
epoch 9818 loss: 0.26040327286702225
epoch 9819 loss: 0.26040253288084336
epoch 9820 loss: 0.26040179307646927
epoch 9821 loss: 0.26040105345383563
epoch 9822 loss: 0.2604003140128776
epoch 9823 loss: 0.2603995747535308
epoch 9824 loss: 0.26039883567573047
epoch 9825 loss: 0.2603980967794119
epoch 9826 loss: 0.26039735806451153
epoch 9827 loss: 0.26039661953096443
epoch 9828 loss: 0.2603958811787057
epoch 9829 loss: 0.2603951430076716
epoch 9830 loss: 0.26039440501779715
epoch 9831 loss: 0.26039366720901924
epoch 9832 loss: 0.2603929295812726
epoch 9833 loss: 0.2603921921344923
epoch 9834 loss: 0.26039145486861603
epoch 9835 loss: 0.26039071778357825
epoch 9836 l

([array([0.97300864]),
  array([0.99853845]),
  array([0.99930191]),
  array([0.98616557]),
  array([0.98668305]),
  array([0.49734041]),
  array([0.97750039]),
  array([0.95281382]),
  array([0.03206072]),
  array([0.00991586]),
  array([0.0247362]),
  array([0.50219908]),
  array([0.02240658])],
 [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [20]:
from sympy import *
x = symbols('x')
sigmoid = 1/(1+exp(-x))
sigmoidg=diff(sigmoid, x)
result=sigmoidg.evalf(subs={x:1})
result

0.196611933241482

In [21]:
sigmoidg

exp(-x)/(1 + exp(-x))**2

# 聚类

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot
from sklearn import svm
from dataset import getData1
import random
n=6 #输入的特征数量
m=6 #实际使用的特征数量
X,y,X_test,y_test=getData1(1)
def kmeans(X,cluster_num,max_epoch=100):
    X=np.array(X)
    def calcu_dist(x1,x2):
        return np.sqrt(sum((x1-x2)*(x1-x2)))
    def choose_random_ls(num):
        ans=[]
        for i in range(cluster_num):
            r=random.randint(0,num)
            while(r in ans):
                r=random.randint(0,num)
            ans.append(r)
        return ans
    def judge(x1,x2):
        for i in range(len(x1)):
            if list(x1[i])!=list(x2[i]):
                return False
        return True
    num=len(X)
    center_ls=choose_random_ls(num-1)
    center_ls=np.array([X[i] for i in center_ls])
    epoch=0
    while True:
        clusters=[[] for i in range(cluster_num)]
        for i in range(len(X)):
            mindist=100000000
            mini=-1
            for j in range(len(center_ls)):
                d=calcu_dist(center_ls[j],X[i])
                if d < mindist:
                    mini=j
                    mindist=d
            clusters[mini].append(i)
        new_center_ls=[]
        for i in range(len(center_ls)):
            idls=clusters[i]
            x=X[idls].mean(axis=0)
            new_center_ls.append(x)
        new_center_ls=np.array(new_center_ls)
        if judge(list(new_center_ls),list(center_ls)) or epoch>=max_epoch:
            break
        center_ls=new_center_ls
        if epoch%10==0:
            print("epoch%d done"%epoch)
        epoch+=1
    return center_ls
center_ls=kmeans(X,3)
center_ls

epoch0 done


array([[0.71428571, 0.71428571, 1.14285714, 1.14285714, 1.71428571,
        0.57142857],
       [0.6       , 2.        , 0.8       , 0.6       , 0.4       ,
        0.2       ],
       [1.8       , 1.6       , 0.4       , 1.6       , 0.4       ,
        0.        ]])

In [29]:
np.array([1,2,3])==np.array([1,2,3])

array([ True,  True,  True])

# 数据降维-PCA与LDA

## PCA

https://blog.csdn.net/qq_20135597/article/details/95247381

## lda
https://github.com/lda-project/lda.git

https://github.com/cemoody/lda2vec.git

In [17]:
import numpy as np
from sklearn.decomposition import PCA
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
pca = PCA(n_components=2)
newX = pca.fit_transform(X)     #等价于pca.fit(X) pca.transform(X)
invX = pca.inverse_transform(X)  #将降维后的数据转换成原始数据
print(X)
print(newX)
print(invX)
print(pca.explained_variance_ratio_)

[[-1 -1]
 [-2 -1]
 [-3 -2]
 [ 1  1]
 [ 2  1]
 [ 3  2]]
[[ 1.38340578  0.2935787 ]
 [ 2.22189802 -0.25133484]
 [ 3.6053038   0.04224385]
 [-1.38340578 -0.2935787 ]
 [-2.22189802  0.25133484]
 [-3.6053038  -0.04224385]]
[[ 0.2935787   1.38340578]
 [ 1.13207093  1.92831932]
 [ 1.42564963  3.3117251 ]
 [-0.2935787  -1.38340578]
 [-1.13207093 -1.92831932]
 [-1.42564963 -3.3117251 ]]
[0.99244289 0.00755711]


# 集成学习

adaboost
xgboost
bagging

In [14]:
from xgboost import XGBClassifier 
from dataset import *
model = XGBClassifier(n_estimators=50, colsample_bytree = 0.3,objective ='binary:logitraw',max_depth = 4, alpha = 0.5,eval_metric='logloss',subsample=0.5,scale_pos_weight=1.5,min_child_weight =0.3) 
X,y,X_test,y_test=getData1()
model.fit(X, y) 
pred = model.predict_proba(X_test)[:, 1] 
print(pred) 

C:\Users\fzc\Anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[1.3998272  0.29639953 0.5791759 ]


# 半监督学习

https://blog.csdn.net/weixin_43008804/article/details/105485566